# -*-Makefile-*-
#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------

CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(PICFLAGS) $(GENFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CCFLAGS        =  
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -D_REENTRANT -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=500 -Wall -Wno-unused-function -I"../../../../include" -I"../../../../include/sys" -I"../../../../include/dcps/C++/SACPP" -I"../../../../include/streams/SACPP" -I"." -I"../../../../examples/include" -I"../../../../examples"
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"." -L"../../../../lib" -Wl,-rpath,\$$ORIGIN -Wl,-rpath,\$$ORIGIN/../../../../lib
CCC           = $(CXX)
MAKEFILE      = Makefile.SA_Cxx_StreamsThroughput_Types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O3 -DNDEBUG
LDLIBS        = -l"streamssacpp" -l"dcpssacpp" -l"ddskernel" -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = .obj$(CFG)/ThroughputStreamsDcps_impl$(OBJEXT) .obj$(CFG)/ThroughputStreamsDcps$(OBJEXT) .obj$(CFG)/ThroughputStreams$(OBJEXT) .obj$(CFG)/ThroughputStreamsSplDcps$(OBJEXT) .obj$(CFG)/ThroughputDcps_impl$(OBJEXT) .obj$(CFG)/ThroughputSplDcps$(OBJEXT) .obj$(CFG)/ThroughputDcps$(OBJEXT) .obj$(CFG)/Throughput$(OBJEXT) .obj$(CFG)/ThroughputStreams_impl$(OBJEXT)
AREXT         = .a
LIB           = $(LTARGETDIR)$(LIBPREFIX)SA_Cxx_StreamsThroughput_Types$(LIBSUFFIX)$(AREXT)
SOEXT         = .so
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)SA_Cxx_StreamsThroughput_Types$(LIBSUFFIX)$(SOEXT)
SHFLAGS       = -shared
SRC           = ThroughputStreamsDcps_impl.cpp ThroughputStreamsDcps.cpp ThroughputStreams.cpp ThroughputStreamsSplDcps.cpp ThroughputDcps_impl.cpp ThroughputSplDcps.cpp ThroughputDcps.cpp Throughput.cpp ThroughputStreams_impl.cpp
LINK.cc       = $(LD) $(LDFLAGS)
DYNAMICFLAGS  = -DOSPL_BUILDEXAMPLE_LIB -DOSPL_BUILDEXAMPLE_LIB
EXPORTFLAGS   = $(DYNAMICFLAGS)

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(SHLIB)

$(SHLIB): $(OBJS)
	@$(TESTDIRSTART) "$(SHTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(SHTARGETDIR)"
	$(LINK.cc) $(SHFLAGS) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

$(LIB): $(OBJS)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	$(AR) $(ARFLAGS) $(LIB) $(OBJS) 

GENERATED_DIRTY = ThroughputDcps_impl.h ThroughputStreams.idl ThroughputDcps_impl.cpp ThroughputSplDcps.cpp ThroughputDcps.cpp Throughput.cpp ThroughputStreams_impl.cpp ThroughputStreamsApi.h ccpp_Throughput.h ThroughputDcps.h Throughput.h ThroughputStreams_impl.h ThroughputSplDcps.h ThroughputStreams.h ThroughputStreamsDcps_impl.cpp ThroughputStreamsDcps.cpp ThroughputStreams.cpp ThroughputStreamsSplDcps.cpp ccpp_ThroughputStreams.h ThroughputStreamsDcps.h ThroughputStreamsSplDcps.h ThroughputStreamsDcps_impl.h

export DYLD_LIBRARY_PATH := $(DYLD_LIBRARY_PATH):../../../../bin:../../../../lib
export LD_LIBRARY_PATH   := $(LD_LIBRARY_PATH):../../../../bin:../../../../lib
export SHLIB_PATH        := $(SHLIB_PATH):../../../../bin:../../../../lib
export LIBPATH           := $(LIBPATH):../../../../bin:../../../../lib
export PATH              := $(PATH):../../../../bin:../../../../lib

.NOTPARALLEL:
ThroughputDcps_impl.h ThroughputStreams.idl ThroughputDcps_impl.cpp ThroughputSplDcps.cpp ThroughputDcps.cpp Throughput.cpp ThroughputStreams_impl.cpp ThroughputStreamsApi.h ccpp_Throughput.h ThroughputDcps.h Throughput.h ThroughputStreams_impl.h ThroughputSplDcps.h: ../idl/Throughput.idl
	"../../../../bin/idlpp" -I "../../../../etc/idl" -l cpp ../idl/Throughput.idl

export DYLD_LIBRARY_PATH := $(DYLD_LIBRARY_PATH):../../../../bin:../../../../lib
export LD_LIBRARY_PATH   := $(LD_LIBRARY_PATH):../../../../bin:../../../../lib
export SHLIB_PATH        := $(SHLIB_PATH):../../../../bin:../../../../lib
export LIBPATH           := $(LIBPATH):../../../../bin:../../../../lib
export PATH              := $(PATH):../../../../bin:../../../../lib

.NOTPARALLEL:
ThroughputStreams.h ThroughputStreamsDcps_impl.cpp ThroughputStreamsDcps.cpp ThroughputStreams.cpp ThroughputStreamsSplDcps.cpp ccpp_ThroughputStreams.h ThroughputStreamsDcps.h ThroughputStreamsSplDcps.h ThroughputStreamsDcps_impl.h: ThroughputStreams.idl
	"../../../../bin/idlpp" -I "../../../../etc/idl" -l cpp -i -I ../idl ThroughputStreams.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(OBJS): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

.obj$(CFG)/ThroughputStreamsDcps_impl$(OBJEXT): ThroughputStreamsDcps_impl.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ThroughputStreamsDcps_impl.cpp

.obj$(CFG)/ThroughputStreamsDcps$(OBJEXT): ThroughputStreamsDcps.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ThroughputStreamsDcps.cpp

.obj$(CFG)/ThroughputStreams$(OBJEXT): ThroughputStreams.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ThroughputStreams.cpp

.obj$(CFG)/ThroughputStreamsSplDcps$(OBJEXT): ThroughputStreamsSplDcps.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ThroughputStreamsSplDcps.cpp

.obj$(CFG)/ThroughputDcps_impl$(OBJEXT): ThroughputDcps_impl.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ThroughputDcps_impl.cpp

.obj$(CFG)/ThroughputSplDcps$(OBJEXT): ThroughputSplDcps.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ThroughputSplDcps.cpp

.obj$(CFG)/ThroughputDcps$(OBJEXT): ThroughputDcps.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ThroughputDcps.cpp

.obj$(CFG)/Throughput$(OBJEXT): Throughput.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Throughput.cpp

.obj$(CFG)/ThroughputStreams_impl$(OBJEXT): ThroughputStreams_impl.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) ThroughputStreams_impl.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(SHLIB) $(LIB)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) .obj$(CFG)/

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) $(CHK_SOURCES)

